### PR TITLE
Add support for Bearer Token Authorization in Solr SQLAlchemy driver

### PR DESCRIPTION
**Pull request by rohitpawar2811**
This commit introduces support for using bearer tokens as part of the authentication mechanism in the SQLAlchemy Solr driver. The changes include:

- Added a new method to handle the creation of a session with proper authorization, allowing the use of bearer tokens.
- Updated the existing authentication logic to conditionally include the bearer token in the authorization headers.
- Ensured that the session can be utilized in other methods within the class.
@aadel

### CODE REVIEW

**Comment by aadel** [comment]
Hi @rohitpawar2811 Thank you for your contribution! LGTM however I had to replace all `url.query` occurrences with `kwargs` in `http.py` to get to work on Superset [3.1.0rc2](https://github.com/apache/superset/releases/tag/3.1.0rc2). Otherwise, when using `url.query`, the following error is returned:

`[SQL: connect() got an unexpected keyword argument 'token']`

What is the environment used at your end?

File: sqlalchemy_solr/http.py [hunk 1]
```diff
@@ -63,6 +65,10 @@ def create_connect_args(self, url, **kwargs):
                 if kwargs["use_ssl"] in [True, "True", "true"]:
                     self.proto = "https://"
 
+            if "token" in url.query:
```
Comment (aadel) [inline sqlalchemy_solr/http.py:68]: Should `url.query` be replaced with `kwargs` in this block?

Comment (rohitpawar2811) [reply sqlalchemy_solr/http.py:68]: Actually, I am using superset 3.0.0

Comment (rohitpawar2811) [reply sqlalchemy_solr/http.py:68]: and I have tested that kwargs did not receive the use_ssl or token, that's why I have to use url.query

solr://172.20.20.245:8443/solr/enterpriseSearch?token=xyz&use_ssl=true

Comment (aadel) [reply sqlalchemy_solr/http.py:68]: Yeah, looks like `**kwargs` is no longer used.

Comment (rohitpawar2811) [reply sqlalchemy_solr/http.py:68]: Thanks for quick merge,I am sending one more PR related to SSL support Fix its a small change
